license = "MIT"
loaderVersion = "[38,)"
modLoader = "javafml"
[[mods]]
displayName = "LootBeams"
modId = "lootbeams"
version = "1.18.2"
logoFile = "banner.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/loot-beams"
authors = "shiroroku(elise)"
credits = "amo"
description = '''
Renders highly configurable colored beams on dropped items!
'''
[[dependencies.lootbeams]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "[38,)"
[[dependencies.lootbeams]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.18,1.19)"
